# Note: this is only an example for development environments.
services:
  reminder-app:
    # Ensure first DB migration has been done before running the app service. 
    image: nicolausc/reminder-discord-bot:latest
    restart: on-failure:3
    volumes:
      - ./app/src/main/resources/env.dev.properties:/app/config/env.properties
      - db-migrations:/app/db
  reminder-db:
    image: postgres:16.2-alpine
    restart: on-failure:3
    ports:
    - "5432:5432"
    environment:
      POSTGRES_PASSWORD: reminderdiscordbot
      POSTGRES_USER: reminderdiscordbot
      POSTGRES_DB: reminderdiscordbot
    volumes: 
      - reminder-db:/var/lib/postgresql/data
  reminder-liquibase:
    # To run DB migration, exec inside and run 'liquibase update',
    # the container can be stopped afterwards as it is no longer used.
    image: liquibase:4.29-alpine
    command: sleep infinity
    environment:
      LIQUIBASE_COMMAND_DRIVER: org.postgresql.Driver
      LIQUIBASE_COMMAND_CHANGELOG_FILE: ./changelog/migrations.sql
      LIQUIBASE_COMMAND_URL: jdbc:postgresql://reminder-db:5432/reminderdiscordbot
      LIQUIBASE_COMMAND_USERNAME: reminderdiscordbot
      LIQUIBASE_COMMAND_PASSWORD: reminderdiscordbot
    volumes:
      - db-migrations:/liquibase/changelog
volumes:
  reminder-db:
    driver: local
  db-migrations:
    driver: local
